# Generated by Django 6.0.2 on 2026-05-04 02:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_ext', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='help_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
