# Generated by Django 6.0.8 on 2026-09-11 17:53

import django.db.models.deletion
import wagtail.contrib.forms.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_ext', '0002_alter_formfield_help_text'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepsFormPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Text shown above the form explaining its purpose.')),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True, help_text='Text shown after a successful submission.')),
                ('privacy_notice', wagtail.fields.RichTextField(blank=True, help_text='Privacy/anonymity notice shown near the form. Important for complaint forms where submitters may want assurance of confidentiality.')),
            ],
            options={
                'verbose_name': 'Representative Finder Form',
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page'),
        ),
    ]
