# Generated by Django 6.0.8 on 2026-09-11 17:57

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_ext', '0004_repsformfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repsformfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='forms_ext.repsformpage'),
        ),
    ]
