# Generated by Django 6.0.8 on 2026-09-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_ext', '0005_alter_repsformfield_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repsformpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='RepsFormField',
        ),
        migrations.DeleteModel(
            name='RepsFormPage',
        ),
    ]
