# Generated by Django 6.0.8 on 2026-09-14 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rep_finder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repsformpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='RepsFormField',
        ),
        migrations.DeleteModel(
            name='RepsFormPage',
        ),
    ]
