# Generated by Django 6.0.8 on 2026-09-15 01:03

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rep_finder', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repsformpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Text shown above the form explaining its purpose.'),
        ),
        migrations.AddField(
            model_name='repsformpage',
            name='thank_you_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Text shown after a successful submission.'),
        ),
    ]
