# Generated by Django 6.0.2 on 2026-02-15 03:19

import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Event Index Page',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for single-day events.', null=True)),
                ('start_time', models.TimeField(blank=True, help_text='Leave blank for all-day events.', null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('branch', models.CharField(choices=[('senate', 'Student Senate'), ('eboard', 'Executive Board'), ('uc', 'Undergraduate Council'), ('gc', 'Graduate Council'), ('jboard', 'Judicial Board'), ('all', 'All / General')], default='all', help_text='Which branch hosts this event.', max_length=20)),
                ('event_type', models.CharField(choices=[('meeting', 'Meeting'), ('hearing', 'Hearing'), ('election', 'Election'), ('social', 'Social Event'), ('workshop', 'Workshop'), ('symposium', 'Symposium'), ('other', 'Other')], default='meeting', max_length=30)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_note', models.CharField(blank=True, help_text="Informational only, e.g. 'Every Monday at 7pm'.", max_length=255)),
                ('external_link', models.URLField(blank=True, help_text='Link to Zoom, external event page, etc.')),
            ],
            options={
                'verbose_name': 'Event',
                'ordering': ['-start_date', '-start_time'],
            },
            bases=('wagtailcore.page',),
        ),
    ]
