# Generated by Django 6.0.2 on 2026-02-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='is_recurring',
        ),
        migrations.AddField(
            model_name='eventpage',
            name='recurrence_end_date',
            field=models.DateField(blank=True, help_text='When the recurrence stops. Required for repeating events.', null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='recurrence_frequency',
            field=models.CharField(choices=[('none', 'Does not repeat'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Every two weeks'), ('monthly', 'Monthly')], default='none', help_text='How often this event repeats.', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='recurrence_note',
            field=models.CharField(blank=True, help_text="Human-readable note, e.g. 'Every Monday at 7pm during Fall semester'.", max_length=255),
        ),
    ]
