"""
Django settings for stugov project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from pathlib import Path
import os

from django.core.exceptions import ImproperlyConfigured

PROJECT_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = PROJECT_DIR.parent
DATA_DIR = Path(os.environ.get("DATA_DIR", BASE_DIR / "data"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    # Project apps — listed first so their templates/static files take priority.
    # Django discovers templates by searching INSTALLED_APPS in order, so our
    # apps override Wagtail defaults when template names collide.
    "sso",
    "branches",
    "events",
    "records",
    "forms_ext",
    "blog",
    "home",
    "search",
    # Wagtail contrib modules — optional Wagtail features enabled as needed.
    # "forms" powers the complaint form builder. "settings" provides the
    # SiteSettings singleton. "routable_page" lets EventIndexPage serve a
    # JSON API endpoint at a sub-URL.
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.contrib.settings",
    "wagtail.contrib.routable_page",
    # Wagtail core modules — order doesn't matter here, but they must all
    # be present for Wagtail to function.
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    # Third-party libraries that Wagtail depends on.
    # modelcluster: enables draft editing of related objects (InlinePanel).
    # taggit: powers Wagtail's tagging system.
    # django_filters: used by Wagtail's API and admin filtering.
    "modelcluster",
    "taggit",
    "django_filters",
    # Campus OIDC authentication. The provider is configured from environment
    # variables below, so secrets never need to be stored in the database.
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.openid_connect",
    # Django built-in apps.
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
]

ROOT_URLCONF = "stugov.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            PROJECT_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # This context processor makes SiteSettings (social links,
                # contact info, etc.) available in every template as
                # {{ settings.home.SiteSettings.field_name }}.
                # Without it, you'd have to pass settings manually in
                # every view's get_context() method.
                "wagtail.contrib.settings.context_processors.settings",
            ],
        },
    },
]

WSGI_APPLICATION = "stugov.wsgi.application"

AUTHENTICATION_BACKENDS = [
    # Keep Django's backend for Wagtail permissions and local break-glass users.
    "django.contrib.auth.backends.ModelBackend",
    # Authenticate users associated with a campus OIDC SocialAccount.
    "allauth.account.auth_backends.AuthenticationBackend",
]


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": DATA_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    PROJECT_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "static"
STATIC_URL = "/static/"

MEDIA_ROOT = DATA_DIR / "media"
MEDIA_URL = "/media/"

# Default storage settings
# See https://docs.djangoproject.com/en/6.0/ref/settings/#std-setting-STORAGES
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Django sets a maximum of 1000 fields per form by default, but particularly complex page models
# can exceed this limit within Wagtail's page editor.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000

# Email settings

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "")

# Wagtail settings

WAGTAIL_SITE_NAME = "RPI Student Government"

# Search
# https://docs.wagtail.org/en/stable/topics/search/backends.html
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
WAGTAILADMIN_BASE_URL = os.environ.get(
    "WAGTAILADMIN_BASE_URL", "https://sg.rpi.edu"
).rstrip("/")

# Allowed file extensions for documents in the document library.
# This can be omitted to allow all files, but note that this may present a security risk
# if untrusted users are allowed to upload files -
# see https://docs.wagtail.org/en/stable/advanced_topics/deploying.html#user-uploaded-files
WAGTAILDOCS_EXTENSIONS = ['csv', 'docx', 'key', 'odt', 'pdf', 'pptx', 'rtf', 'txt', 'xlsx', 'zip']

# Allow HTML in form-field help_text. Required because forms_ext.FormField
# overrides help_text to be a RichTextField — without this flag, Wagtail's
# FormBuilder calls conditional_escape() on the stored rich text before it
# reaches the template, and the <p>/<strong>/etc. tags render as literal
# text instead of formatting.
# Safe here because only Wagtail admins (not end users) author help_text.
WAGTAILFORMS_HELP_TEXT_ALLOW_HTML = True


# Campus OpenID Connect

def env_bool(name, default=False):
    """Read a conventional boolean environment variable."""
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


OIDC_ENABLED = env_bool("OIDC_ENABLED")
OIDC_PROVIDER_ID = "campus"
OIDC_PROVIDER_NAME = "CMS"
OIDC_SERVER_URL = os.environ.get("OIDC_SERVER_URL", "").rstrip("/")
OIDC_CLIENT_ID = os.environ.get("OIDC_CLIENT_ID", "")
OIDC_CLIENT_SECRET = os.environ.get("OIDC_CLIENT_SECRET", "")
OIDC_SCOPES = tuple(
    scope for scope in os.environ.get("OIDC_SCOPES", "openid").split() if scope
)
OIDC_ROLE_CLAIM_PATH = os.environ.get("OIDC_ROLE_CLAIM_PATH", "groups").strip()
OIDC_POST_LOGOUT_REDIRECT_URI = f"{WAGTAILADMIN_BASE_URL}/"

if OIDC_ENABLED:
    required_oidc_settings = {
        "OIDC_SERVER_URL": OIDC_SERVER_URL,
        "OIDC_CLIENT_ID": OIDC_CLIENT_ID,
        "OIDC_CLIENT_SECRET": OIDC_CLIENT_SECRET,
        "OIDC_ROLE_CLAIM_PATH": OIDC_ROLE_CLAIM_PATH,
    }
    missing_oidc_settings = [
        name for name, value in required_oidc_settings.items() if not value
    ]
    if missing_oidc_settings:
        raise ImproperlyConfigured(
            "OIDC is enabled but these settings are empty: "
            + ", ".join(missing_oidc_settings)
        )
    if not OIDC_SERVER_URL.startswith("https://"):
        raise ImproperlyConfigured("OIDC_SERVER_URL must use HTTPS")
    if not WAGTAILADMIN_BASE_URL.startswith("https://"):
        raise ImproperlyConfigured("WAGTAILADMIN_BASE_URL must use HTTPS with OIDC")

# allauth is used only as an OIDC relying party. Local password authentication
# remains available through Wagtail and Django's own admin login pages.
SOCIALACCOUNT_ONLY = True
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_STORE_TOKENS = False
SOCIALACCOUNT_REQUESTS_TIMEOUT = 5
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_ADAPTER = "sso.adapter.CampusSocialAccountAdapter"
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_UNIQUE_EMAIL = True

SOCIALACCOUNT_PROVIDERS = {}
if OIDC_ENABLED:
    SOCIALACCOUNT_PROVIDERS = {
        "openid_connect": {
            "APPS": [
                {
                    "provider_id": OIDC_PROVIDER_ID,
                    "name": OIDC_PROVIDER_NAME,
                    "client_id": OIDC_CLIENT_ID,
                    "secret": OIDC_CLIENT_SECRET,
                    "settings": {
                        "server_url": OIDC_SERVER_URL,
                        "scope": OIDC_SCOPES,
                        "oauth_pkce_enabled": True,
                        # This campus issuer is authoritative for its email
                        # claim even though it omits email_verified.
                        "verified_email": True,
                        "email_authentication": True,
                    },
                }
            ]
        }
    }
    WAGTAILADMIN_LOGIN_URL = f"/accounts/oidc/{OIDC_PROVIDER_ID}/login/"
