# Generated by Django 6.0.2 on 2026-02-15 03:19

import django.db.models.deletion
import modelcluster.fields
import modelsearch.index
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('branch_type', models.CharField(choices=[('senate', 'Student Senate'), ('eboard', 'Executive Board'), ('uc', 'Undergraduate Council'), ('gc', 'Graduate Council'), ('jboard', 'Judicial Board')], help_text='Which branch of student government this page represents.', max_length=20)),
                ('tagline', models.CharField(blank=True, help_text='Short description shown prominently on the landing page.', max_length=255)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('document_list', 6), ('call_to_action', 11), ('info_cards', 18), ('box_embed', 22), ('raw_html', 23), ('blockquote', 24)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 5: ('wagtail.blocks.ListBlock', (4,), {}), 6: ('wagtail.blocks.StructBlock', [[('heading', 3), ('documents', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': "Button/link text, e.g. 'Get Involved' or 'View Constitution'", 'max_length': 100, 'required': True}), 8: ('wagtail.blocks.URLBlock', (), {'help_text': 'External URL. Leave blank if linking to an internal page.', 'required': False}), 9: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Internal page link. Takes precedence over external URL if both are set.', 'required': False}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary Button'), ('secondary', 'Secondary Button'), ('link', 'Text Link')]}), 11: ('wagtail.blocks.StructBlock', [[('text', 7), ('url', 8), ('page', 9), ('style', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'required': True}), 13: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional icon name (e.g., a Heroicon name for Tailwind)', 'required': False}), 15: ('wagtail.blocks.URLBlock', (), {'required': False}), 16: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 17: ('wagtail.blocks.StructBlock', [[('title', 12), ('text', 13), ('icon', 14), ('link', 15), ('link_page', 16)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {'icon': 'grip'}), 19: ('wagtail.blocks.URLBlock', (), {'help_text': 'Box shared link URL for the folder or file to embed.', 'required': True}), 20: ('wagtail.blocks.IntegerBlock', (), {'default': 500, 'help_text': 'Height of the embedded viewer in pixels.'}), 21: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption below the embed.', 'required': False}), 22: ('wagtail.blocks.StructBlock', [[('box_url', 19), ('height', 20), ('caption', 21)]], {}), 23: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Use sparingly. For embedding widgets, iframes, or custom HTML.'}), 24: ('wagtail.blocks.BlockQuoteBlock', (), {})}, help_text='Flexible content area for the branch landing page.')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('meeting_schedule', wagtail.fields.RichTextField(blank=True, help_text="Regular meeting times and location, e.g. 'Mondays 7pm, Union 3602'.")),
            ],
            options={
                'verbose_name': 'Branch Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ClassCouncilIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Class Council Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ClassCouncilPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('class_year', models.PositiveIntegerField(help_text='Graduation year, e.g. 2027')),
                ('description', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Class Council Page',
                'ordering': ['-class_year'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CommitteeIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Committee Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CommitteePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('meeting_time', models.CharField(blank=True, help_text="e.g. 'Tuesdays 5pm'", max_length=200)),
                ('meeting_location', models.CharField(blank=True, help_text="e.g. 'Union Room 3602'", max_length=200)),
            ],
            options={
                'verbose_name': 'Committee Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FlexiblePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('document_list', 6), ('call_to_action', 11), ('info_cards', 18), ('box_embed', 22), ('raw_html', 23), ('blockquote', 24)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 5: ('wagtail.blocks.ListBlock', (4,), {}), 6: ('wagtail.blocks.StructBlock', [[('heading', 3), ('documents', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': "Button/link text, e.g. 'Get Involved' or 'View Constitution'", 'max_length': 100, 'required': True}), 8: ('wagtail.blocks.URLBlock', (), {'help_text': 'External URL. Leave blank if linking to an internal page.', 'required': False}), 9: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Internal page link. Takes precedence over external URL if both are set.', 'required': False}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary Button'), ('secondary', 'Secondary Button'), ('link', 'Text Link')]}), 11: ('wagtail.blocks.StructBlock', [[('text', 7), ('url', 8), ('page', 9), ('style', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'required': True}), 13: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional icon name (e.g., a Heroicon name for Tailwind)', 'required': False}), 15: ('wagtail.blocks.URLBlock', (), {'required': False}), 16: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 17: ('wagtail.blocks.StructBlock', [[('title', 12), ('text', 13), ('icon', 14), ('link', 15), ('link_page', 16)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {'icon': 'grip'}), 19: ('wagtail.blocks.URLBlock', (), {'help_text': 'Box shared link URL for the folder or file to embed.', 'required': True}), 20: ('wagtail.blocks.IntegerBlock', (), {'default': 500, 'help_text': 'Height of the embedded viewer in pixels.'}), 21: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption below the embed.', 'required': False}), 22: ('wagtail.blocks.StructBlock', [[('box_url', 19), ('height', 20), ('caption', 21)]], {}), 23: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Use sparingly. For embedding widgets, iframes, or custom HTML.'}), 24: ('wagtail.blocks.BlockQuoteBlock', (), {})})),
            ],
            options={
                'verbose_name': 'Flexible Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MemberListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introductory text shown above the member grid.')),
            ],
            options={
                'verbose_name': 'Member Listing Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('class_year', models.PositiveIntegerField(blank=True, help_text='Graduation year, e.g. 2027', null=True)),
                ('major', models.CharField(blank=True, max_length=200)),
                ('bio', wagtail.fields.RichTextField(blank=True, help_text='Short bio. Keep it to 2-3 sentences.')),
                ('is_active', models.BooleanField(default=True, help_text="Uncheck when member leaves office. Inactive members won't appear on public listings.")),
                ('photo', models.ForeignKey(blank=True, help_text='Headshot or profile photo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Member Profile',
                'verbose_name_plural': 'Member Profiles',
                'ordering': ['last_name', 'first_name'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='CommitteeMemberPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('committee_role', models.CharField(choices=[('chair', 'Chair'), ('vice_chair', 'Vice Chair'), ('member', 'Member')], default='member', max_length=50)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_members', to='branches.committeepage')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='branches.memberprofile')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassCouncilMemberPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('role', models.CharField(help_text="Role within the class council, e.g. 'President' or 'Social Chair'.", max_length=100)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='council_members', to='branches.classcouncilpage')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='branches.memberprofile')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BranchMemberPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('role', models.CharField(choices=[('president', 'President'), ('vice_president', 'Vice President'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('senator', 'Senator'), ('representative', 'Representative'), ('chair', 'Committee Chair'), ('vice_chair', 'Vice Chair'), ('member', 'Member'), ('chief_justice', 'Chief Justice'), ('justice', 'Justice')], max_length=50)),
                ('role_title_override', models.CharField(blank=True, help_text="Custom title that overrides the role dropdown, e.g. 'President of the Senate' instead of just 'President'.", max_length=100)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_placements', to='branches.memberlistingpage')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='branches.memberprofile')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
