# Generated by Django 6.0.2 on 2026-02-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchmemberplacement',
            name='role',
            field=models.CharField(choices=[('president_union', 'President of the Union'), ('vice_president', 'Vice President'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('senator', 'Senator'), ('council_president', 'Council President'), ('representative', 'Representative'), ('chair', 'Committee Chair'), ('vice_chair', 'Vice Chair'), ('member', 'Member'), ('chief_justice', 'Chief Justice'), ('justice', 'Justice')], max_length=50),
        ),
    ]
