# Generated by Django 6.0.2 on 2026-02-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_alter_branchmemberplacement_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchpage',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
