# Generated by Django 6.0.2 on 2026-02-17 21:48
# Manually edited to handle ImageField -> ForeignKey conversion on SQLite.
#
# The original ImageField stored a filename string. The new ForeignKey stores
# an integer ID. SQLite can't convert between these in-place, so we:
#   1. Remove the old column (losing any uploaded filename — the image wasn't
#      stored via Wagtail's image library anyway, so it's not recoverable)
#   2. Add the new column as a nullable integer FK

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branchpage_image'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        # Step 1: Drop the old varchar image column
        migrations.RemoveField(
            model_name='branchpage',
            name='image',
        ),
        # Step 2: Add the new FK image column
        migrations.AddField(
            model_name='branchpage',
            name='image',
            field=models.ForeignKey(
                blank=True,
                help_text='Photo representing this branch (e.g. a group photo or meeting).',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailimages.image',
            ),
        ),
    ]
