# Generated by Django 6.0.2 on 2026-02-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_alter_branchpage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchmemberplacement',
            name='role',
            field=models.CharField(choices=[('president_union', 'President of the Union'), ('vice_president', 'Vice President'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('grand_marshall', 'Grand Marshal'), ('senator', 'Senator'), ('council_president', 'Council President'), ('representative', 'Representative'), ('chair', 'Committee Chair'), ('vice_chair', 'Vice Chair'), ('member', 'Member'), ('chief_justice', 'Chief Justice'), ('justice', 'Justice')], max_length=50),
        ),
    ]
