# Generated by Django 6.0.2 on 2026-02-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_alter_branchmemberplacement_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchmemberplacement',
            name='role',
        ),
        migrations.AddField(
            model_name='branchmemberplacement',
            name='roles',
            field=models.JSONField(default=list, help_text='One or more roles this member holds on this page.'),
        ),
    ]
