# Generated by Django 6.0.2 on 2026-02-19 05:25

import branches.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_remove_branchmemberplacement_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchmemberplacement',
            name='roles',
            field=branches.models.MultiSelectField(choices=[('president_union', 'President of the Union'), ('vice_president', 'Vice President'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('grand_marshal', 'Grand Marshal'), ('vice_grand_marshal', 'Vice Grand Marshal'), ('senator', 'Senator'), ('council_president', 'Council President'), ('representative', 'Representative'), ('chair', 'Committee Chair'), ('vice_chair', 'Vice Chair'), ('member', 'Member'), ('chief_justice', 'Chief Justice'), ('justice', 'Justice'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('parliamentarian', 'Parliamentarian'), ('liaison', 'Liaison')], default=list, help_text='One or more roles this member holds on this page.'),
        ),
    ]
