# Generated by Django 6.0.2 on 2026-02-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_remove_branchmemberplacement_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchmemberplacement',
            name='roles',
            field=models.JSONField(default=list, help_text='One or more roles this member holds on this page.'),
        ),
    ]
