# Generated by Django 6.0.2 on 2026-04-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0007_alter_branchmemberplacement_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchmemberplacement',
            name='roles',
            field=models.JSONField(default=list, help_text='One or more roles this member holds on this page.'),
        ),
    ]
