# Generated by Django 6.0.2 on 2026-04-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0008_alter_branchmemberplacement_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchmemberplacement',
            name='chairs_title_override',
            field=models.CharField(blank=True, help_text="Title shown in the Committee Chairs section only, e.g. 'Academic Affairs Chair'.", max_length=100, verbose_name='Committee Chairs title override'),
        ),
        migrations.AddField(
            model_name='branchmemberplacement',
            name='members_title_override',
            field=models.CharField(blank=True, help_text="Title shown in the Members section only, e.g. 'Class of 2027 Senator'.", max_length=100, verbose_name='Members title override'),
        ),
        migrations.AddField(
            model_name='branchmemberplacement',
            name='officers_title_override',
            field=models.CharField(blank=True, help_text='Title shown in the Officers section only.', max_length=100, verbose_name='Officers title override'),
        ),
        migrations.AddField(
            model_name='branchmemberplacement',
            name='presiding_title_override',
            field=models.CharField(blank=True, help_text='Title shown in the Presiding Officer section only.', max_length=100, verbose_name='Presiding Officer title override'),
        ),
        migrations.AlterField(
            model_name='branchmemberplacement',
            name='role_title_override',
            field=models.CharField(blank=True, help_text='Fallback custom title used in any tier where no tier-specific override is set. Leave blank to show the role name from the dropdown.', max_length=100, verbose_name='Default title override'),
        ),
    ]
