# Generated by Django 6.0.6 on 2026-06-30 20:43

import branches.models
import django.db.models.deletion
import modelcluster.fields
import modelsearch.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0009_branchmemberplacement_chairs_title_override_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Displayed role text, e.g. 'Class of 2027 Representative'.", max_length=255)),
                ('branch', models.CharField(choices=[('senate', 'Student Senate'), ('eboard', 'Executive Board'), ('uc', 'Undergraduate Council'), ('gc', 'Graduate Council'), ('jboard', 'Judicial Board')], help_text='Which branch this role belongs to.', max_length=20)),
                ('tier', models.CharField(choices=[('presiding', 'Presiding Officer'), ('officers', 'Officers'), ('chairs', 'Committee Chairs'), ('members', 'Members'), ('advisors', 'Club Financial Advisors')], default='members', help_text="Display rank on the member listing page. 'Club Financial Advisors' sort to the bottom.", max_length=20)),
                ('constituency_class', models.CharField(choices=branches.models.constituency_class_choices, default='none', help_text='Graduating class this role represents, if any.', max_length=20)),
                ('constituency_fsl', models.CharField(blank=True, choices=[('associated', 'FSL-Associated'), ('independent', 'Independent'), ('none', 'No FSL Association')], help_text='FSL group this role represents, if any.', max_length=20, verbose_name='Constituency FSL association')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['branch', 'name'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.RemoveField(
            model_name='branchmemberplacement',
            name='chairs_title_override',
        ),
        migrations.RemoveField(
            model_name='branchmemberplacement',
            name='members_title_override',
        ),
        migrations.RemoveField(
            model_name='branchmemberplacement',
            name='officers_title_override',
        ),
        migrations.RemoveField(
            model_name='branchmemberplacement',
            name='presiding_title_override',
        ),
        migrations.RemoveField(
            model_name='branchmemberplacement',
            name='role_title_override',
        ),
        migrations.RemoveField(
            model_name='branchmemberplacement',
            name='roles',
        ),
        migrations.CreateModel(
            name='BranchMemberRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('placement', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='branches.branchmemberplacement')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='branches.role')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
