# Generated by Django 6.0.2 on 2026-08-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0010_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='tier',
            field=models.CharField(choices=[('presiding', 'Presiding Officer'), ('officers', 'Officers'), ('chairs', 'Committee Chairs'), ('members', 'Members'), ('advisors', 'Non-voting Members')], default='members', help_text="Display rank on the member listing page. 'Club Financial Advisors' sort to the bottom.", max_length=20),
        ),
    ]
