# Generated by Django 6.0.8 on 2026-09-24 02:14

import sys
from django.db import migrations, models


def transfer_rcs_id(apps, schema_editor):
    MemberProfile = apps.get_model('branches', 'MemberProfile')
    i = 1
    for profile in MemberProfile.objects.all():
        if profile.email == "":
            profile.rcs_id = f"NULL{i}"
            i = i + 1
            sys.stdout.write(f"\n\033[93m\033[1mWARNING:\033[0m\033[93m Member '{profile.first_name} {profile.last_name}' has no email and has been assigned RCS ID '{profile.rcs_id}'.\033[0m")
            sys.stdout.flush()
        else:
            profile.rcs_id = str(profile.email).split('@', 1)[0]
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0013_remove_branchmemberrole_placement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='Role name, text in [brackets] will not be displayed.', max_length=255),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='rcs_id',
            field=models.CharField(null=True, max_length=9, verbose_name='RCS ID'),
        ),
        migrations.RunPython(
            transfer_rcs_id,
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='email',
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='rcs_id',
            field=models.CharField(max_length=9, unique=True, verbose_name='RCS ID'),
        ),
    ]
