# Generated by Django 6.0.2 on 2026-02-15 03:19
# Manually edited to handle RichTextField -> StreamField data migration.
#
# WHY THIS MIGRATION IS SPLIT INTO TWO STEPS:
#
# The original auto-generated migration tried to alter the body field
# from RichTextField (stores plain HTML string) to StreamField (stores
# JSON) in a single step. But SQLite's JSON_VALID constraint rejects
# the old HTML data during the column copy.
#
# The fix:
#   Step 1: Add all new fields, create SiteSettings, etc. (everything
#           EXCEPT the body field change)
#   Step 2: Run a Python function to convert existing body HTML to
#           StreamField JSON format
#   Step 3: Alter the body column type to StreamField
#
# The data conversion wraps old HTML in a StreamField paragraph block:
#   Before: "<p>Welcome to student government</p>"
#   After:  [{"type": "paragraph", "value": "<p>Welcome to...</p>", "id": "..."}]

import json
import uuid

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


def convert_body_to_streamfield_json(apps, schema_editor):
    """
    Convert existing body RichTextField content to StreamField JSON format.

    This runs BEFORE the column type changes, while body is still a text
    column. We write valid JSON into it so the subsequent AlterField
    (which adds the JSON_VALID constraint) will succeed.
    """
    HomePage = apps.get_model("home", "HomePage")
    for page in HomePage.objects.all():
        old_body = page.body
        if old_body and old_body.strip():
            # Wrap the HTML in a StreamField paragraph block
            streamfield_data = json.dumps([
                {
                    "type": "paragraph",
                    "value": old_body,
                    "id": str(uuid.uuid4())[:8],
                }
            ])
            page.body = streamfield_data
        else:
            # Empty body → empty StreamField list
            page.body = "[]"
        page.save(update_fields=["body"])


def reverse_body_conversion(apps, schema_editor):
    """
    Reverse migration: extract HTML from StreamField JSON back to plain text.
    """
    HomePage = apps.get_model("home", "HomePage")
    for page in HomePage.objects.all():
        try:
            data = json.loads(page.body)
            if data and isinstance(data, list):
                # Concatenate all paragraph block values
                html_parts = [
                    block["value"]
                    for block in data
                    if block.get("type") == "paragraph"
                ]
                page.body = "".join(html_parts)
            else:
                page.body = ""
        except (json.JSONDecodeError, TypeError):
            pass  # Already plain text, leave it
        page.save(update_fields=["body"])


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        # --- Step 1: Create SiteSettings, add new HomePage fields ---
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_url', models.URLField(blank=True, verbose_name='Discord Invite URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter/X URL')),
                ('contact_email', models.EmailField(blank=True, help_text='e.g. union_officers@union.lists.rpi.edu', max_length=254, verbose_name='General Contact Email')),
                ('office_location', models.CharField(blank=True, help_text="e.g. 'Student Government Suite, 3rd Floor, Rensselaer Union'", max_length=255)),
                ('office_hours', models.CharField(blank=True, help_text="e.g. 'Mon-Fri 9am-5pm'", max_length=255)),
                ('footer_text', wagtail.fields.RichTextField(blank=True)),
                ('box_archive_url', models.URLField(blank=True, help_text='Link to the main Box folder for archival documents.', verbose_name='Box Archive URL')),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(blank=True, help_text='Shown below the main title in the hero section.', max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, default='RPI Student Government', max_length=255),
        ),
        # --- Step 2: Convert existing body data to JSON ---
        migrations.RunPython(
            convert_body_to_streamfield_json,
            reverse_body_conversion,
        ),
        # --- Step 3: Now alter the column type (JSON_VALID constraint is safe) ---
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('info_cards', 9), ('call_to_action', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'required': True}), 4: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional icon name (e.g., a Heroicon name for Tailwind)', 'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'required': False}), 7: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title', 3), ('text', 4), ('icon', 5), ('link', 6), ('link_page', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'icon': 'grip', 'label': 'Info Cards'}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': "Button/link text, e.g. 'Get Involved' or 'View Constitution'", 'max_length': 100, 'required': True}), 11: ('wagtail.blocks.URLBlock', (), {'help_text': 'External URL. Leave blank if linking to an internal page.', 'required': False}), 12: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Internal page link. Takes precedence over external URL if both are set.', 'required': False}), 13: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary Button'), ('secondary', 'Secondary Button'), ('link', 'Text Link')]}), 14: ('wagtail.blocks.StructBlock', [[('text', 10), ('url', 11), ('page', 12), ('style', 13)]], {})}),
        ),
        # --- Step 4: Create HomePageQuickLink ---
        migrations.CreateModel(
            name='HomePageQuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_text', models.CharField(max_length=100)),
                ('link_url', models.URLField(blank=True, help_text='External URL. Used only if no internal page is selected.')),
                ('icon_class', models.CharField(blank=True, help_text='Optional CSS/icon class for visual decoration.', max_length=50)),
                ('link_page', models.ForeignKey(blank=True, help_text='Internal page to link to. Takes priority over external URL.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_links', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
