# Generated by Django 6.0.2 on 2026-02-17 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_sitesettings_alter_homepage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltHomePage',
            fields=[
                ('homepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.homepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.homepage',),
        ),
    ]
