# Generated by Django 6.0.2 on 2026-07-10 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_althomepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AltHomePage',
        ),
    ]
