# Generated by Django 6.0.2 on 2026-02-15 03:19

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Record Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RecordPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('record_type', models.CharField(choices=[('minutes', 'Meeting Minutes'), ('constitution', 'Constitution'), ('bylaws', 'Bylaws'), ('resolution', 'Resolution'), ('report', 'Report'), ('policy', 'Policy Document'), ('budget', 'Budget'), ('other', 'Other')], default='minutes', max_length=20)),
                ('date_published', models.DateField(help_text='Date the record was published or approved.')),
                ('academic_year', models.CharField(blank=True, help_text="e.g. '2025-2026'. Used for filtering.", max_length=9)),
                ('summary', wagtail.fields.RichTextField(blank=True, help_text="Brief summary of the record's contents.")),
                ('body', wagtail.fields.RichTextField(blank=True, help_text="Full text content (if the record isn't just an attached file).")),
                ('branch', models.CharField(choices=[('senate', 'Student Senate'), ('eboard', 'Executive Board'), ('uc', 'Undergraduate Council'), ('gc', 'Graduate Council'), ('jboard', 'Judicial Board'), ('general', 'General / All')], default='general', max_length=20)),
                ('is_public', models.BooleanField(default=True, help_text='Uncheck to restrict viewing to logged-in users only.')),
            ],
            options={
                'verbose_name': 'Record',
                'ordering': ['-date_published'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RecordDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('version_label', models.CharField(blank=True, help_text="e.g. 'v2.1' or 'Amended 2025-03'.", max_length=50)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.document')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='records.recordpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
