# Generated by Django 6.0.2 on 2026-02-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordpage',
            name='box_embed_height',
            field=models.PositiveIntegerField(default=600, help_text='Height in pixels for the embedded Box viewer.'),
        ),
        migrations.AddField(
            model_name='recordpage',
            name='box_url',
            field=models.URLField(blank=True, help_text='Paste the Box shared link for this document. The page will show an embedded viewer so visitors can preview and download directly from Box. This is the preferred approach for public records — Box is the single source of truth.', verbose_name='Box shared link'),
        ),
    ]
