# Generated by Django 6.0.2 on 2026-04-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_recordpage_box_embed_height_recordpage_box_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxFileCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_file_id', models.CharField(help_text="Box's unique file ID.", max_length=64, unique=True)),
                ('name', models.CharField(help_text='Filename as it appears in Box.', max_length=500)),
                ('record_type', models.CharField(choices=[('minutes', 'Meeting Minutes'), ('agenda', 'Agenda'), ('motion', 'Motion'), ('constitution', 'Constitution'), ('bylaws', 'Bylaws'), ('resolution', 'Resolution'), ('report', 'Report'), ('budget', 'Budget'), ('other', 'Other')], default='other', max_length=20)),
                ('box_folder_path', models.CharField(blank=True, help_text="Path of parent folders within Box (e.g. 'Senate/Minutes').", max_length=1000)),
                ('shared_link', models.URLField(blank=True, help_text='Box shared link URL for direct access.')),
                ('size', models.BigIntegerField(default=0, help_text='File size in bytes.')),
                ('modified_at', models.DateTimeField(blank=True, help_text='Last modified timestamp from Box.', null=True)),
                ('synced_at', models.DateTimeField(auto_now=True, help_text='When this cache entry was last updated by sync.')),
            ],
            options={
                'verbose_name': 'Box File (cached)',
                'verbose_name_plural': 'Box Files (cached)',
                'ordering': ['-modified_at'],
            },
        ),
    ]
